/* Havnekaptajnen - offline cache. No analytics, no remote assets. */
const CACHE='havnekaptajnen-static-v54';
const STATIC=['./voyages.js?v=14.0.0','./voyages.css?v=14.0.0','./archipelago-v14.png','./harbor-life.js?v=13.0.1','./harbor-life.css?v=14.0.0','./sponsors.js?v=13.0.0','./sponsor.html','./sejlstroem-logo.avif','./om-spillet.html','./spilinfo.css?v=12.1.1','./spilinfo.js?v=13.0.0','./land.js?v=12.1.0','./land.css?v=12.1.0','./workshop-floor-v12.png?v=12.1.0','./land-meadow.png?v=12.1.0','./land-greenhouse.png?v=12.1.0','./land-bakery.png?v=12.1.0','./land-ropeworks.png?v=12.1.0','./land-sailmaker.png?v=12.1.0','./fleet-feeder.png','./fleet-ocean.png','./fleet.js?v=14.0.0','./fleet.css?v=14.0.0','./fleet-cutter.png','./fleet-cruiser.png','./fleet-catamaran.png','./fleet-expedition.png','./','./index.html','./harbor-content.js?v=13.0.0','./billing-client.js?v=12.1.0','./shop.css?v=12.1.0','./styles.css?v=12.1.0','./app.js?v=14.0.0','./walking.js?v=12.1.0','./camera.js?v=12.1.0','./walking-rig.js?v=12.1.0','./island-worker-rig.png','./island-alma-rig.png','./world.css?v=12.1.0','./campaign.css?v=12.1.0','./growth.css?v=12.1.0','./island.css?v=12.1.0','./island-terrain.png','./island-fishery.png','./island-workshop.png','./island-cafe.png','./island-lighthouse.png','./island-boat.png','./island-interior.png','./island-tree.png','./island-worker.png','./island-alma.png','./island-water.png','./harbor-start.png','./harbor-world.png','./workshop-world.png','./player-boat.png','./boat-top.png','./manifest.webmanifest','./icons/icon.svg','./icons/icon-192.png','./icons/icon-512.png','./icons/icon-maskable-512.png'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(STATIC.map(url=>new Request(url,{cache:'reload'})))).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('havnekaptajnen-static-')&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;
 if(event.request.mode==='navigate')event.respondWith(fetch(event.request).catch(async()=>{const page='./'+url.pathname.replace(/^\//,'');return (await caches.match(page))||caches.match('./index.html');}));
 else event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(c=>c.put(event.request,copy));}return response;})));
});

