/* Original destinations. Stable identifiers keep journeys and discoveries intact. */
(function(root){
 'use strict';
 const regions=[{id:0,name:'Det nære øhav',text:'De første ture fra din egen bro.'},{id:1,name:'Handelsøerne',text:'Frugt, træ, mel og sejl til en havn i vækst.'},{id:2,name:'Det store hav',text:'Lange rejser, stærke skrog og havne til de store skibe.'}];
 const destinations=[
  {id:'maage',name:'Mågeø',subtitle:'Drivtømmer langs stranden',seconds:35,needs:{fish:2},cash:220,reward:{wood:4},unlock:0,requires:[],hull:0,chapter:1,capacity:0,story:'Freja har samlet drivtømmer efter vinterens storme. Du hjælper med at få det hjem.'},
  {id:'skaer',name:'De blå skær',subtitle:'Træværk mellem klipperne',seconds:55,needs:{fish:2},cash:400,reward:{plank:4},unlock:1,requires:['navigation'],hull:0,chapter:1,capacity:0,story:'Ved det røde skur mellem skærene venter tørt træ. Navigationsudstyr hjælper dig gennem den smalle rende.'},
  {id:'fyr',name:'Fyrø',subtitle:'Forsyninger til fyrpasseren',seconds:70,needs:{coffee:2},cash:650,reward:{beans:6,fish:4},unlock:2,requires:['battery'],hull:0,chapter:1,capacity:0,story:'Nora bytter bønner og fisk for en varm kop. Batteriforsyning er nødvendig på denne længere spilrute.'},
  {id:'vinter',name:'Vinterholm',subtitle:'Lys i vinterhavnen',seconds:90,needs:{coffee:2,smoked:2},cash:1000,reward:{plank:6,wood:6},unlock:3,requires:['heater','battery'],hull:1,chapter:1,capacity:0,story:'En lille vinterhavn venter på forsyninger. Varme, batteri og et stærkere skrog får dig frem i spillet.'},
  {id:'aeble',name:'Æbleholm',subtitle:'Frugt fra den grønne ø',seconds:150,needs:{fish:2,plank:1},cash:800,reward:{apple:6,grain:4},unlock:1,requires:[],hull:1,chapter:3,capacity:20,story:'Idas familie dyrker frugt bag læmuren. Hjælp med mad og træ, og tag høsten med til dit eget bageri.'},
  {id:'tommer',name:'Tømmerø',subtitle:'Skovens gamle savmølle',seconds:240,needs:{coffee:2,fish:2},cash:1000,reward:{wood:7,plank:5},unlock:2,requires:['navigation'],hull:2,chapter:7,capacity:32,story:'Vandhjulet driver øens savværk. De store træstammer kræver et rummeligt lastdæk.'},
  {id:'molle',name:'Mølleø',subtitle:'Mel og morgenbrød',seconds:420,needs:{plank:2,smoked:2},cash:1200,reward:{grain:5,bread:5},unlock:3,requires:['battery'],hull:4,chapter:12,capacity:48,story:'Mølleren sender brød til hele øhavet. Medbring materialer til møllen og få en frisk last med hjem.'},
  {id:'sejl',name:'Sejlø',subtitle:'Reb og dug til værftet',seconds:720,needs:{coffee:2,bread:2},cash:1600,reward:{rope:6,cloth:4},unlock:4,requires:['navigation'],hull:6,chapter:20,capacity:80,story:'På det blå værft bliver der snoet reb og vævet dug. Øens håndværk hjælper dig med stærkere broer og nye sejl.'},
  {id:'basalt',name:'Basaltø',subtitle:'Forsyninger til havforskerne',seconds:1200,needs:{bread:2,coffee:2},cash:1800,reward:{plank:6,rope:4},unlock:4,requires:['battery','navigation'],hull:8,chapter:30,capacity:160,story:'Forskerne måler vind og vand ved de mørke klipper. Her er åbent hav, så både skrog og rækkevidde skal være klar.'},
  {id:'storhavn',name:'Storhavn',subtitle:'Containerkajen i læ',seconds:1800,needs:{plank:2,rope:2},cash:2000,reward:{cloth:6,sail:4},unlock:4,requires:['navigation'],hull:8,chapter:35,capacity:240,port:1,story:'Handelshavnens kraner tager imod din containerlast. Din egen erhvervsbro og containerkaj skal være færdige først.'},
  {id:'isfjord',name:'Isfjord',subtitle:'Ekspedition mod nord',seconds:3600,needs:{coffee:2,bread:2,smoked:2},cash:2200,reward:{fish:6,plank:4},unlock:4,requires:['heater','battery'],hull:10,chapter:45,capacity:400,story:'En lille station holder øje med isen. De varme forsyninger kommer langt omkring, når dit skib er klar til de kolde farvande.'},
  {id:'horisont',name:'Horisontø',subtitle:'Handel på den anden side',seconds:7200,needs:{sail:1,bread:2,coffee:2},cash:2500,reward:{rope:6,cloth:6},unlock:4,requires:['navigation','battery'],hull:12,chapter:60,capacity:600,port:2,story:'Bag det åbne hav ligger øhavets store handelsplads. Sejl fra din dybhavskaj, og lad de lange ture finansiere havnens næste kapitel.'}
 ].map((d,i)=>({...d,region:Math.floor(i/4),art:i,x:[12.5,37.5,62.5,87.5][i%4],y:[16.67,50,83.33][Math.floor(i/4)]}));
 const api=Object.freeze({regions,destinations});if(typeof module==='object'&&module.exports)module.exports=api;else root.HarborVoyages=api;
})(typeof window==='undefined'?globalThis:window);
